### ISSUE TITLE
What license is this released under

### ISSUE THREAD

**Issue by JasperFloorBloomreach** [dkoudela/active-directory-to-openldap#2]
My company has a product which supports integration via ldap. We officially support AD (among others) as that supports ldap. I now have a need to test some issues with our integration and AD. I run my tests against an in memory server rather than any persistent server. I was looking for and AD schema which you seem to have created. However it doesn't seem to have any licence information attached. I was wondering under what licence your project is released. We don't package our tests in our binary but if I used this it would be available in our source which is available to users of our project. While some of our code is open source, this is part of our enterprise offering so it would only be available to customers.

**Comment by dkoudela** [comment]
Hi,
In this particular project, I have no concrete preference concerning the license.
Often I use GNU GENERAL PUBLIC LICENSE Version 2.
Would it work for you?
Thanks,
David.

**Comment by JasperFloorBloomreach** [comment]
Hi, 
The GNU license isn't usable for us. Any of the following would work for us:
Apache License v2.0
Apache License v1.1
PHP 3.01
BSD-2 or BSD-3
DOM4J License
MIT / X11
ICU
W3C Software License
University of Illinois/NCSA
Academic Free License 3.0
Creative Commons Attribution (CC-A) 2.5/3.0
Creative Commons Copyright-Only Dedication
Python Software Foundation License
Eclipse Distribution License 1.0

**Comment by dkoudela** [comment]
It is incorporated in commit:
https://github.com/dkoudela/active-directory-to-openldap/commit/18f49d16605b9b297d341da87ad99a6c0c840081

Thanks,
David.
