### ISSUE TITLE
Ad to Openldap schema issue 

### ISSUE THREAD

**Issue by victory412** [dkoudela/active-directory-to-openldap#3]
Hi Team,

I am getting below issue while run the set-content.sh with testdata.ldif
ldap_add: Object class violation (65)
        additional info: object class 'mstop' requires attribute 'instanceType' 

Kindly help us on this

**Comment by victory412** [comment]
Please help someone

**Comment by dkoudela** [comment]
This issue has been fixed.
Best Regards,
David.
